
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM amazoncorretto:17-alpine
MAINTAINER Duarte Carla Aneley
COPY target/cad-0.0.1-SNAPSHOT.jar cad-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/cad-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
