
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM amazoncorretto:17-alpine-jdk
MAINTAINER Duarte Carla Aneley
COPY target/cad-0.0.1-SNAPSHOT.jar cad-app.jar
ENTRYPOINT ["java", "-jar", "/cad-app.jar"]

